### ISSUE TITLE
Add news feed/page

### ISSUE THREAD

**Issue by nicebread** [FelixHenninger/de-rn#10]
Should look good even when it is rarely updated ...

**Comment by FelixHenninger** [comment]
First draft is [now available](https://de-rn.netlify.app/activity/). Should the RatSWD item still be added to the news?

**Comment by nicebread** [comment]
Looks nice! What happens when more and more news accumulate? Do we create an archive, or an endless scrolling website?

Skip the RatSWD item.

**Comment by FelixHenninger** [comment]
Thanks! At present, the overview page shows the four latest news items and the four next events. The treatment of the archive is something we should discuss -- there is an archive at https://de-rn.netlify.app/activity/news/ , which is paginated and therefore won't overflow. The decision to make is how prominently to link there (e.g. you could choose to make the news more ephemeral). There's a lot of things on the site, not all of which are linked up -- would be thrilled to discuss details!

Best, -Felix
