### ISSUE TITLE
Create and Implement BUA Logo as a Founding Member (incl. funding notice)

### ISSUE THREAD

**Issue by StefanieWeigold** [FelixHenninger/de-rn#12]
Zusammenstellung eines Logos aus fünf einzelnen:
BUA Logo und darunter FU, HU, TU, Charité Logo, in dieser Reihenfolge
plus Förderhinweis anführen: "Gefördert im Rahmen der Exzellenzstrategie von Bund und Ländern durch die Berlin University Alliance 
Funded through the Berlin University Alliance as part of the Excellence Strategy of the German federal and state governments"

**Comment by FelixHenninger** [comment]
Completed in September/October, closing issue.
