### ISSUE TITLE
Add lightweight visitor tracking

### ISSUE THREAD

**Issue by nicebread** [FelixHenninger/de-rn#13]
Maybe Matomo? I have an instance running on my server.

**Comment by FelixHenninger** [comment]
Quite possibly I'm wrong, but if I'm not mistaken we might have that in place? We inject [a tracking snippet](https://github.com/FelixHenninger/de-rn/blob/master/templates/partials/tracking.html) into all pages, is it not coming through on your side?

**Comment by nicebread** [comment]
My fault - in fact we already do this ;-) I forgot it.
